// La base de donnees du dashboard, decoupee par domaine. Ce fichier ne fait
// que rassembler : require("./db") donne les memes fonctions qu'avant.
//
//   connexion   ouverture (paresseuse), transactions
//   migrations  schema versionne
//   journal     historique affiche en bas du dashboard
//   arrivees    fichiers recus par le bot, inscrits avant traitement
//   reglages    stocks, jeton d'impression, petits reglages
//   montants    tarifs et arrondi au centime
//   expediteurs creation, tarifs, dettes, fusions
//   colis       arrivee, modifications, ajouts et retraits a la main
//   impression  file d'impression, impression automatique
//   tournee     depart, sac, cloture
//   drops       ce qui part, et son annulation
//   stats       series de revenus
//   abonnements notifications push
//   sql         fragments SQL partages

const {
  db,
  transaction,
  ouvreBase,
  fermeBase,
  cheminBase,
} = require("./connexion");
const {
  DEFAULT_PRICE,
  DEFAULT_LIT_PRICE,
  DEFAULT_BJ_PRICE,
  arrondiCentimes,
} = require("./montants");
const {
  journalise,
  avecSource,
  getJournal,
} = require("./journal");
const {
  inscritArrivee,
  getArrivee,
  arriveeLiee,
  arriveeFaite,
  arriveeRatee,
  arriveesEnAttente,
} = require("./arrivees");
const {
  getPrintToken,
  getStock,
  getStocks,
  adjustStock,
  consumeStock,
  getStatsMessageId,
  setStatsMessageId,
  getSetting,
  setSetting,
} = require("./reglages");
const {
  getOrCreateSender,
  updateSenderPrices,
  getDebtsBySender,
  markSenderPaid,
  getMergeCandidates,
  mergeSendersIntoOther,
  mergeSenderInto,
} = require("./expediteurs");
const {
  addColis,
  createBatch,
  findColisByMessage,
  findAnyColisByMessage,
  getLatestBatchId,
  setColisType,
  setBatchType,
  setColisPrice,
  setColisCarrier,
  setColisMessage,
  saveCarrierRule,
  getCarrierRules,
  listCarrierRules,
  clearCarrierRules,
  getUnclassifiedPending,
  setBatchCarrier,
  getColisById,
  getBatchColis,
  deleteColis,
  setBatchPrice,
  setColisNote,
  setBatchNote,
  quickAddColis,
  quickRemoveColis,
  getPendingSummary,
  countColisSince,
  summarizeNewColis,
} = require("./colis");
const {
  getPrintableColis,
  getPrintableSummary,
  countAlreadyPrinted,
  getLitPrintable,
  countLitPrintable,
  countLitNoted,
  isAutoPrintEnabled,
  setAutoPrintEnabled,
  getUnprintedLabels,
  countUnprintedLabels,
  markPrinted,
  getPrintJobs,
  getPrintJobColis,
} = require("./impression");
const {
  getTourStart,
  getTourSelection,
  getTourSelectionNoms,
  getTourChoix,
  getHorsTournee,
  startTour,
  endTour,
  recordTour,
  getDayTours,
  saveLastTour,
  getLastTour,
  clearLastTour,
  serverNow,
  tourScope,
  getArrivedDuringTour,
} = require("./tournee");
const {
  evenements,
  undropColis,
  restoreStock,
  getCarrierSummary,
  dropByCarrier,
  dropAll,
  dropAllExceptLit,
  dropBySender,
  dropColis,
} = require("./drops");
const {
  getDailySeries,
  getWeeklySeries,
  getBestDay,
} = require("./stats");
const {
  markPushSeen,
  setPushAnnounced,
  saveSubscription,
  deleteSubscription,
  listSubscriptions,
  countSubscriptions,
} = require("./abonnements");
const { FREE_STATUS } = require("./sql");

module.exports = {
  FREE_STATUS,
  db,
  transaction,
  ouvreBase,
  fermeBase,
  cheminBase,
  DEFAULT_PRICE,
  DEFAULT_LIT_PRICE,
  DEFAULT_BJ_PRICE,
  arrondiCentimes,
  journalise,
  avecSource,
  getJournal,
  inscritArrivee,
  getArrivee,
  arriveeLiee,
  arriveeFaite,
  arriveeRatee,
  arriveesEnAttente,
  getPrintToken,
  getStock,
  getStocks,
  adjustStock,
  consumeStock,
  getStatsMessageId,
  setStatsMessageId,
  getSetting,
  setSetting,
  getOrCreateSender,
  updateSenderPrices,
  getDebtsBySender,
  markSenderPaid,
  getMergeCandidates,
  mergeSendersIntoOther,
  mergeSenderInto,
  addColis,
  createBatch,
  findColisByMessage,
  findAnyColisByMessage,
  getLatestBatchId,
  setColisType,
  setBatchType,
  setColisPrice,
  setColisCarrier,
  setColisMessage,
  saveCarrierRule,
  getCarrierRules,
  listCarrierRules,
  clearCarrierRules,
  getUnclassifiedPending,
  setBatchCarrier,
  getColisById,
  getBatchColis,
  deleteColis,
  setBatchPrice,
  setColisNote,
  setBatchNote,
  quickAddColis,
  quickRemoveColis,
  getPendingSummary,
  countColisSince,
  summarizeNewColis,
  getPrintableColis,
  getPrintableSummary,
  countAlreadyPrinted,
  getLitPrintable,
  countLitPrintable,
  countLitNoted,
  isAutoPrintEnabled,
  setAutoPrintEnabled,
  getUnprintedLabels,
  countUnprintedLabels,
  markPrinted,
  getPrintJobs,
  getPrintJobColis,
  getTourStart,
  getTourSelection,
  getTourSelectionNoms,
  getTourChoix,
  getHorsTournee,
  startTour,
  endTour,
  recordTour,
  getDayTours,
  saveLastTour,
  getLastTour,
  clearLastTour,
  serverNow,
  tourScope,
  getArrivedDuringTour,
  evenements,
  undropColis,
  restoreStock,
  getCarrierSummary,
  dropByCarrier,
  dropAll,
  dropAllExceptLit,
  dropBySender,
  dropColis,
  getDailySeries,
  getWeeklySeries,
  getBestDay,
  markPushSeen,
  setPushAnnounced,
  saveSubscription,
  deleteSubscription,
  listSubscriptions,
  countSubscriptions,
};
